service: hackerzlab15


custom:
  stage: ${opt:stage, self:provider.stage}
  func_prefix: ${self:service}-${self:custom.stage}
  private: false # Change to 'true' if you don't want to 

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "arn:aws:lambda:${self:provider.region}:*:function:*"


functions:
  Q12:
    handler: handler.Q12
    events: 
      - http:
          path: Q12
          method: get
  Q13:
    handler: handler.Q13
    events: 
      - http:
          path: Q13
          method: POST
  Q14:
    handler: handler.Q14
    events: 
      - http:
          path: Q14_POST
          method: post
  Q15:
    handler: handler.Q15
    events: 
      - http:
          path: Q15
          method: post
 
